// Generated by dts-bundle v0.7.3

const _default: (content: string) => {
    type: string;
    line: number;
    colStart: number;
    colEnd: number;
    name: string;
}[];
export default _default;

type stringIndexBool = {
    [key: string]: boolean;
};
export const whiteSpace: RegExp;
export const whiteSpaceObj: stringIndexBool;
export const variableCharsObj: stringIndexBool;
export const CommentSemiColon: RegExp;
export const startingMultiLineComment: RegExp;
export const endingMultiLineComment: RegExp;
export {};

